bin/hunter, lib/flight_hunter/server/list.rb, lib/flight_hunter/server/modify_group.rb, lib/flight_hunter/server/rename_group.rb
All nodes can now be part of a group. By default their group is "none" which means that the group in data is nil.
Added several functions to do with groups:
Rename_group allows user to rename a group. All nodes within the group will be shown to have a differently named group.
Modify-group allows user to modify a node's groups. Any number of groups can be added or removed in a single command, to a single node.
Changed List-Parsed to display groups in addition to what it displayed previously.
Changed Show to display groups in addition to what it displayed previously.
=> Added groups

lib/hunter/commands/modify_label.rb
- Replaced non-existent `modify_label` method call with use of the setter provided by `attr_accessor`.
Resolves #13 when merged.
=> Replace method call that doesn't exist

lib/hunter/commands/hunt.rb
As title. Means that when `target_host` is set, the hunting node will note down a relevant IP instead of just `localhost`.
=> Use target host when sending to self if possible

lib/hunter/commands/hunt.rb
This PR updates the `hunt` command to load in the buffer and parsed lists every loop when a new node is picked up. Race conditions with reading/saving the buffer list are impossible because the process only ever runs on one thread, refusing new nodes until the 'current' one has been resolved.
Resolves #18 when merged.
=> Reload the node lists each time a new node is found

lib/hunter/cli.rb, lib/hunter/commands/hunt.rb, lib/hunter/commands/send.rb, lib/hunter/node.rb
This PR gives the option to send three additional strings with the `send` command - `label`, `prefix` and `group`. All are stored as attributes of the node, and are sent out alongside the payload.
=> Expand send command

lib/hunter/commands/modify_groups.rb, lib/hunter/commands/remove_node.rb, lib/hunter/commands/show.rb
This PR fixes the `show`, `remove-node` and `modify-group` commands when using the `--buffer` option.
=> Pass buffer to search_field

lib/hunter/commands/hunt.rb, lib/hunter/commands/send.rb
This PR sets the `send` command's payload to be YAML data representing the information it was previously sending. This comes with some advantages:
* Adding/removing fields from the payload is easier
* Data can be received on a machine running `hunt` from any machine that may send a HTTP POST request - requests with a content type of `hunter-node` will be read, while other data received on the chosen port will be ignored (originally this would create a blank/broken entry in the buffer). Other machines don't necessarily need to use Flight-Hunter to send this data.
* Although less useful, this change also allows the `send` command to send data to sources besides machines running `hunt` - I can't think of any use cases for this myself but it's still bonus functionality.
=> Improved payload sending

lib/hunter/commands/hunt.rb
Previously, attempting to run the listening server with the `--include-self` flag was causing the server to stop accepting calls from any other machine, leading them to timeout. This seems to solve the issue.
=> Fix hanging when `--include-self` used

etc/config.yml.ex, lib/hunter/cli.rb, lib/hunter/commands/hunt.rb, lib/hunter/commands/send.rb, lib/hunter/config.rb
This PR introduces some basic authentication for data sent/received. Sent data now has an `auth_key` field, which defaults to a value set in `config.yml` but may be set either via an environment variable or using the new `--auth` option, which is available in both the `send` and `hunt` commands - should a machine running `hunt` receive data sent to it without matching authentication keys, the `hunt`ing machine notifies the user and the `send`ing machine raises an error informing the user there was an authentication key mismatch.
NB This PR depends heavily on the changes made in #30
=> Authentication on sent messages

lib/hunter/commands/hunt.rb
This PR fixes the clash between the implementation of `--include-self` and `--auth`. A node will now always be authorised when sending to itself.
=> Always authorise self

lib/hunter/commands/parse.rb
This PR adds some extra conditional logic to both the parsing methods to ensure that we don't attempt to use the `--start` option if it hasn't been provided. This PR also ensures that, if it's provided, the `--start` option is validated as a positive integer (although, still contained within a string). A bug was also fixed with regards to checking for duplicate preset labels in the buffer list.
=> Handle invalid start option

bin/hunter, bin/start
This PR enables hunter to dump both standard output and error to a log file at `var/log/log.txt` when it is run as a background process through `flight-service`
=> Log the output of hunter when autorunning

README.md, etc/config.yml.ex, lib/hunter/cli.rb, lib/hunter/commands/hunt.rb, lib/hunter/commands/send.rb, lib/hunter/commands/show.rb, lib/hunter/config.rb, lib/hunter/node.rb, lib/hunter/node_list.rb
This PR converts the `send` command's `--file` option into a more flexible `--command` option, which will be run in the console and its output sent as content.
This PR also makes numerous semantic changes to distinguish between the **payload** (the JSON data which is sent by `send`) and what is now known as the **content** (the data which is sent via the `--command` option).
=> Send command output

lib/hunter/node.rb
This PR ensures that the array returned by `Node` when fetching its groups is always sorted alphabetically.
Resolves #50 when merged.
=> Group ordering

lib/hunter/commands/list.rb, lib/hunter/commands/modify_groups.rb, lib/hunter/commands/parse.rb, lib/hunter/commands/remove_node.rb, lib/hunter/commands/show.rb, lib/hunter/node.rb, lib/hunter/table.rb
This PR aims to be more uniform in how we print nodes in a tabular format.
A new class method has been added to the `Table` class, `::from_nodes`, to return a new `Table` object with rows created from a given `nodes` argument. The headers/rows used differ based on whether or not the nodes being listed are stored in the buffer or the parsed list.
A new instance method has been added to the `Node` class, `#to_table_row`, to return an array containing data to be used in the `Table::from_nodes` method. Again, the data returned depends on the buffer/parsed conditional.
When printing buffer nodes, the following data is shown:
```
┌──────────┬─────────────┬───────────┬───────────┬──────────────────┐
│ ID       │ Hostname    │ IP        │ Groups    │ Presets          │ …
```
=> List unification

lib/hunter/commands/hunt.rb, lib/hunter/commands/list.rb, lib/hunter/commands/parse.rb, lib/hunter/config.rb, lib/hunter/node.rb, lib/hunter/node_list.rb
This PR moves the data for each node into its own file, stored in the relevant directory (`var/buffer` or `var/parsed`). A new `filepath` attribute was added to `Node` to accommodate this. Each file is named using the hostid of the origin node.
A typo in the `list` command was also fixed.
=> Store nodes in individual files

lib/hunter/cli.rb, lib/hunter/commands/hunt.rb, lib/hunter/commands/remove_node.rb
This PR introduces a new option for the `hunt` command. If `--auto-parse EXPR` is used, hunted nodes with names matching the regex `EXPR` will skip the buffer and be added straight to the parsed node list, with the label being either the preset label (if it exists), or the first part of the node's hostname.
NB When a node is hunted, it is should print `Node added to the <buffer/parsed> node list`. The current implementation is made with the new node-file implementation in mind, and as a side effect it currently prints `buffer.yaml` and `parsed.yaml` respectively, instead of just `buffer` and `parsed`, if the nodes aren't being stored in individual files.
=> Automatiically parse nodes

bin/hunter, bin/start
When run through Flight Service, the output of `hunt` is intended to be saved to a log file. This seemed to not be working, and it turns out this was because output on stdout is automatically buffered when not being written to a terminal, so the full log would only be written after stopping the `hunt` process. This PR ensures that stdout is always written to the file without buffering.
The logging process will now also avoid overwriting the previous log, instead appending its own output to the log file if it already exists.
=> Fix error with hunter logging

README.md, etc/config.yml.ex, lib/hunter/commands/hunt.rb, lib/hunter/config.rb
The README was missing a few details from recent PRs; this PR brings it a tad more up to scratch. It also introduces being able to set the auto-parse option for `hunt` as a config key, as otherwise it wouldn't be available to users running `autorun` (and therefore, anyone using the Flight Service implementation).
=> README refresh

etc/config.yml.ex, lib/hunter/cli.rb, lib/hunter/commands/hunt.rb, lib/hunter/config.rb, lib/hunter/profile_cli.rb
NB: This PR is based on changes made in #58 , which should be reviewed/merged _before_ this PR.
This PR introduces changes to the `hunt` command that allows it to attempt to trigger Flight Profile if the node's label matches a given regular expression.
A new config option has been added, `auto_apply`, which allows the user to define a set of rules containing regular expressions and Flight Profile identity names. The rules are defined as follows:
```yaml
auto_apply:
$chead: login
cnode0[1-5]^: compute1
cnode[6-10]^: compute2
```
When a node has been automatically parsed (see #56 ), its label is then checked against the keys of the `auto_apply` rules. The first key that, as a regular expression, matches the node's label, is picked as the auto-apply rule. The value of the chosen key is …
=> Auto apply a profile

lib/hunter/commands/hunt.rb
This PR fixes a bug in which a node would always be applied when hunted regardless of the status of `--auto-apply`.
=> Only auto-apply when option is used

lib/hunter/cli.rb, lib/hunter/commands/hunt.rb, lib/hunter/version.rb
This PR introduces a change to the auto-apply loading process. Previously, Hunter allowed for auto-apply rules to be specified at runtime via the CLI. This introduced touch of malarkey with regards to validating the input, and occasionally it wasn't reading anything from the config file. You can no longer specify the rules at the command line, and it is always initialised to at least an empty hash if the config file has no rules specified.
=> Fix auto-apply rules loading mishap

lib/hunter/profile_cli.rb
When manually parsing a node with `auto_apply` enabled, the terminal would stall for 30s (the timeout duration) before returning control to the user. I believe to have narrowed down the problem to `flight-subprocess` continuing to wait for the `apply` process to complete. `flight-subprocess` already forks out to `profile`, but with this PR `hunter` now also forks out to `flight-subprocess` to avoid having to wait for it to deem the apply command "done".
=> Fix long delay on manual parse

lib/hunter/cli.rb, lib/hunter/commands/remove_node.rb, lib/hunter/node_list.rb
This PR changes the `remove-node` command to accept a comma-separated list of search terms, instead of a single search term. The previous options to switch between buffer/parsed nodelist, match against hostname, and match with regex still exist, although the hostname option has been renamed.
=> Accept multiple node per remove-node command

lib/hunter/commands/hunt.rb
This PR fixes a bug that arises when receiving a malformed packet on a TCP connection. We post the client's address to the logfile, but we try to do it _after_ closing the connection, which raises an error.
=> Close client after trying to access it

lib/hunter/cli.rb, lib/hunter/commands/send.rb
This PR modifies the `SendPayload#retry_interval` method and the retry loop in `SendPayload#run` method to validate the user input for the `--retry-interval` option. It converts the invalid input to a reasonable valid value and also limits the minimum acceptable value. See the Example section below for the demonstration.
- The `SendPayload#retry_interval` will now return a processed valid value, or nil when `--retry-interval` is not enabled.
- The retry loop in `SendPayload#run` method is modified to fit the new logic
```
--retry-interval 12      # 12.0
--retry-interval 12abc   # 12.0
--retry-interval abc12   # 5.0
--retry-interval 0.1     # 5.0
```
=> Retry Input Type Validation

lib/hunter/commands/send.rb
#Overview
Currently, a `NoMethodError` will occur when using autorun in send mode to trigger the `hunter` since there is no @options instance variable exists. This pull request tried to fix it with minimum effort without changing the architecture and mechanism of `autorun` command.
=> safe the empty? call for nil @options.groups in send command

lib/hunter/cli.rb, lib/hunter/commands/send.rb, lib/hunter/config.rb
This branch aims to fix the issue that broadcast is never triggered under autorun scenario.
- Read the broadcast parameter from both @options variable and Config files.
- Change the logic of triggering the broadcast in Command::SendPayload.
- Added a corresponding `broadcast` function in Config class.
- Fix the issue that the port non exists error is never triggered caused by the inappropriate to_s method used
=> Fix the issue that broadcast is never triggered under autorun scenario

lib/hunter/commands/send.rb
This PR updates the `send` command to create a PID file, so that Flight Service can track that it has started. The ability to specify the pidfile path is only accepted through an environment variable, because it's an option meant for us to use instead of users.
=> Create PID file when running send

lib/hunter/commands/hunt.rb, lib/hunter/commands/send.rb
Previously, using `--include-self` would raise an error because the command attempts to create a PID file with the same name as the one created by the `hunt` command. This PR introduces two new changes:
- Un-set `ENV['flight_HUNTER_pidfile']` before running `send` as part of `include-self`
- In the `send` command, don't create a PID file if no environment variable is set.
- If no variable is set, it _probably_ isn't being used as background service, and we don't need to track it's process ID.
=> Don't duplicate PID file when using `include-self`

lib/hunter/commands/hunt.rb
Currently, when the TCP server of a hunt session tries to read the content of a received request, it might get nil and then terminate the TCP thread. While the specific reason has not been discovered yet, this fix aims to handle this situation by raising an error and responding to the client with status code 500 under this nil situation.
=> Handling the Unexpected Nil Line Read by Client TCPSocket

etc/config.yml.ex, lib/hunter/cli.rb, lib/hunter/commands/parse.rb, lib/hunter/config.rb, lib/hunter/node.rb
This PR adds a new option, `--blank`, to the `parse` command. With it set, the hostname will never be used as the default for manual parsing, so if alternative options are not available then the prefilled label will be blank.
=> Add `--blank` option to `parse`

README.md, etc/config.yml.ex, lib/hunter/cli.rb, lib/hunter/commands/parse.rb, lib/hunter/config.rb, lib/hunter/node.rb
This PR fixes a bad interaction between `parse --auto` and the new `--default-hostnames` option. Previously, it was ignored entirely for automatic parsing. With the changes in this PR, it will be considered for both manual and automatic parsing modes. In the event that `parse --auto` is used and `default_hostnames` is set to `blank` (either in the command or in config), then the nodes will not be parsed if any of them generate blank names in this manner.
=> Fix blank hostname for automatic parsing

Gemfile, Gemfile.lock, README.md, lib/hunter/commands/concerns/node_utils.rb, lib/hunter/commands/modify_groups.rb, lib/hunter/commands/remove_node.rb, lib/hunter/commands/show.rb, lib/hunter/node_list.rb
This PR aims to create a single home for logic used to read nodes from the command line.
- The module `NodeUtils` holds methods/classes shared among commands that read nodes from the CLI.
- `CLIParser` accepts the raw CLI input, splits it into an array, and evaluates any square bracket expansion that may exist.
- Regular expressions don't evaluate square brackets, but they're regular expressions so the user can handle that themselves.
- `NodeFetcher` takes an array of search tasks and a list, and fetches every node in that list that matches any of the given search tasks
Each of the `remove-node` and `modify-groups` commands are using the new logic
- They each accept a comma-separated-collection (CSC) of either exact node names, node names with genders-style bracket expansion, or regular …
=> Unify node input approach
